### PR TITLE
https://github.com/wsl2ls/iOS_Tips.git

### PR DESCRIPTION
**Pull request by mfc-pbl-game**
https://github.com/wsl2ls/iOS_Tips.git

### CODE REVIEW

**Comment by odrobnik** [comment]
@mfc-pbl-game what is this about?

**Comment by DivineDominion** [comment]
@odrobnik Looks like GitHub actions setup to auto-build the code. (Don't know if that's useful for an assorted collection of tips, unless you want to make this work with every sub-project to keep the code up-to-date?)

**Comment by odrobnik** [comment]
Sorry, I still don't understand... the sample Code doesn't need to be built...

**Comment by DivineDominion** [comment]
Oh I do agree 100% that this doesn't make sense for this repo. Just wanted to clarify what this would do :)

**Comment by odrobnik** [comment]
So, should I merge this or not?

**Comment by DivineDominion** [comment]
Now that you ask: I wouldn't. There's no need for CI for sample code I use on my blog. When CI breaks, (and I don't want CI for that stuff) I get email notifications that require attention, but what for?

If you want to keep your code up-to-date with Swift version changes, CI might make sense to notify you about failing builds, but I don't know if this configuration really covers that. (Looks like it'd build the repo? but there are many projects inside, so I don't know what'd happen)

**Pull request closed without merging**
